apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ki-dev-dummy-api
  namespace: argocd
spec:
  destination:
    namespace: ki-dev-dummy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/dev
    repoURL: https://github.com/karname-interview/manifests.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
