apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ki-prd-dummy-airflow-configs
  namespace: argocd
spec:
  destination:
    namespace: air
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/prd
    repoURL: https://github.com/karname-interview/airflow_configs.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
